airpnp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

app_name = 'airpnp'
urlpatterns = [
	url(r'^$', views.index, name='index'),
    url(r'^bathrooms/', include('bathrooms.urls')),
    url(r'^admin/', admin.site.urls),
]

bathrooms/urls.py
from django.conf.urls import url
from . import views

app_name = 'bathrooms'
urlpatterns = [
    url(r'^$', views.list, name='list'),
	url(r'^(?P<bathroom_id>[0-9]+)/$', views.detail, name='detail'),
	url(r'^(?P<bathroom_id>[0-9]+)/vote$', views.vote, name='vote'),
]

bathrooms/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404

class Location(models.Model):
	human_readable_location = models.CharField(max_length=100)
	google_maps_link = models.CharField(max_length=50)
	google_maps_embed = models.CharField(max_length=500)
	
	def __str__(self):
		return self.human_readable_location

class Bathroom(models.Model):
	name = models.CharField(max_length=100)
	gender = models.PositiveSmallIntegerField() # 0 = male; 1 = female; 2 = gender-neutral
	urinals = models.PositiveSmallIntegerField()
	stalls = models.PositiveSmallIntegerField()
	handicap_stalls = models.PositiveSmallIntegerField()
	sinks = models.PositiveSmallIntegerField()
	paper_towels = models.PositiveSmallIntegerField()
	hand_dryers = models.PositiveSmallIntegerField()
	windows = models.PositiveSmallIntegerField()
	
	location = models.ForeignKey(Location, on_delete=models.CASCADE)
	location_desc = models.CharField(max_length=300, blank=True)
	
	def __str__(self):
		return self.name

class Rating(models.Model):
	bathroom = models.ForeignKey(Bathroom, on_delete=models.CASCADE)
	cleanliness_rating = models.PositiveSmallIntegerField()
	amenities_rating = models.PositiveSmallIntegerField()
	
	def __str__(self):
		return str(self.cleanliness_rating) + "/" + str(self.amenities_rating) + " rating for " + self.bathroom.name
		
class Image(models.Model):
	bathroom = models.ForeignKey(Bathroom, on_delete=models.CASCADE)
	image = models.ImageField(upload_to='photos/')
	
	def __str__(self):
		return "Image of " + self.bathroom.name

airpnp/views.py
from django.shortcuts import render

def index(request):
	return render(request, 'index.html')

bathrooms/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse
from .models import Bathroom, Rating, Image

def list(request):
	bathroom_list = Bathroom.objects.all()
	
	heading = 'all bathrooms'
	
	filtertype = request.GET.get('filtertype')
	if filtertype == 'singles':
		bathroom_list = Bathroom.objects.filter(urinals=1)
		heading = 'single bathrooms'
	if filtertype == 'mens':
		bathroom_list = Bathroom.objects.filter(gender=0)
		heading = 'men\'s rooms'
	if filtertype == 'womens':
		bathroom_list = Bathroom.objects.filter(gender=1)
		heading = 'women\'s rooms'
	if filtertype == 'genderneutral':
		bathroom_list = Bathroom.objects.filter(gender=2)
		heading = 'gender-neutral rooms'
	
	length = len(bathroom_list)
	
	ratings_list = []
	for bathroom in bathroom_list:
		ratings = Rating.objects.filter(bathroom__id=bathroom.id)
		numberRatings = getRatings(bathroom, ratings)
		starRatings = {
			'cleanliness': numToStars(numberRatings['cleanliness']),
			'amenities': numToStars(numberRatings['amenities']),
		}
		ratings_list.append(starRatings)
	
	view_list = zip(bathroom_list, ratings_list)
	view_list = sorted(view_list, key=lambda bathroom_tuple: bathroom_tuple[0].name)
	view_list = sorted(view_list, key=lambda bathroom_tuple: bathroom_tuple[0].location.human_readable_location)
	
	return render(request, 'bathrooms/list.html', {
		'bathroom_list': view_list,
		'heading': heading,
		'length': length
	})
	
def detail(request, bathroom_id):
	bathroom = get_object_or_404(Bathroom, id=bathroom_id)
	ratings = Rating.objects.filter(bathroom__id=bathroom_id)
	images = Image.objects.filter(bathroom__id=bathroom_id)
	
	results = getRatings(bathroom, ratings)
	cleanliness_rating = results['cleanliness']
	amenities_rating = results['amenities']
	
	cleanliness_stars = numToStars(cleanliness_rating)
	amenities_stars = numToStars(amenities_rating)
		
	gender = 'Men\'s'
	if bathroom.gender == 1:
		gender = 'Women\'s'
	if bathroom.gender == 2:
		gender = 'Gender-neutral'
	
	return render(request, 'bathrooms/bathroom.html', {
		'bathroom': bathroom,
		'cleanliness_rating': cleanliness_rating,
		'amenities_rating': amenities_rating,
		'cleanliness_stars': cleanliness_stars,
		'amenities_stars': amenities_stars,
		'images': images,
		'gender': gender
	})

def vote(request, bathroom_id):
	rating = Rating()
	rating.bathroom = Bathroom.objects.get(id=bathroom_id)
	rating.cleanliness_rating = request.POST.get('cleanliness', None)
	rating.amenities_rating = request.POST.get('amenities', None)
	if rating.cleanliness_rating != None and rating.amenities_rating != None:
		rating.save()
	
	bathroom = get_object_or_404(Bathroom, id=bathroom_id)
	return redirect('bathrooms:detail', bathroom_id)

def getRatings(bathroom, ratings):
	cleanliness_rating_sum = 0
	amenities_rating_sum = 0
	rating_n = 0
	for rating in ratings:
		cleanliness_rating_sum += rating.cleanliness_rating
		amenities_rating_sum += rating.amenities_rating
		rating_n += 1
	
	cleanliness_rating = 'no ratings yet'
	amenities_rating = 'no ratings yet'
	if rating_n > 0:
		cleanliness_rating = cleanliness_rating_sum / rating_n
		amenities_rating = amenities_rating_sum / rating_n
		
	return {
		'cleanliness': cleanliness_rating,
		'amenities': amenities_rating
	}
	
def numToStars(rating):
	if rating == 'no ratings yet':
		return rating
	
	rating = round(rating)
	string = ''
	for i in range(rating):
		string += '&#9733;'
	return string

bathrooms/templates/bathrooms/bathroom.html
{% extends "bathrooms/template.html" %}
{% load static %}

{% block content %}
{% if bathroom %}
	<div id="title">
		<h1>{{ bathroom.name }}</h1>
		<p id="navbutton"><a href="{% url 'bathrooms:list' %}">Back</a></p>
		<h2>{{ gender }}</h2>
	</div>
	
	<div id="everything-but-title">
		<div id="info">
			<div id="stats">
				<p><span class="stat">Urinals</span> <span class="value">{{bathroom.urinals}}</span></p>
				<p><span class="stat">Stalls:</span> <span class="value">{{bathroom.stalls}}</span></p>
				<p><span class="stat">Handicap stalls:</span> <span class="value">{{bathroom.handicap_stalls}}</span></p>
				<p><span class="stat">Sinks:</span> <span class="value">{{bathroom.sinks}}</span></p>
				<p><span class="stat">Paper towel dispensers:</span> <span class="value">{{bathroom.paper_towels}}</span></p>
				<p><span class="stat">Hand dryers:</span> <span class="value">{{bathroom.hand_dryers}}</span></p>
				<p><span class="stat">Windows:</span> <span class="value">{{bathroom.windows}}</span></p>
			</div>
			
			<hr>
			
			<p>Location: <a href="{{ bathroom.location.google_maps_link }}">{{ bathroom.location.human_readable_location }}</a></p>
			<p>{{ bathroom.location_desc }}</p>
			{{ bathroom.location.google_maps_embed|safe|escape }}
			
		</div>
		
		<div id="rating">
			<h2>Rating</h2>
			<p class="score">Cleanliness: <span class="rating_num">{{ cleanliness_rating|floatformat }}</span> <span class="rating_stars">{{ cleanliness_stars|safe|escape }}</span></p>
			<p class="score">Amenities: <span class="rating_num">{{ amenities_rating|floatformat }}</span> <span class="rating_stars">{{ amenities_stars|safe|escape }}</span></p>
			
			<div id="images">
			{% if images|length == 0 %}
				<p id="noimages">no images yet</p>
			{% else %}
				{% for image in images %}
					<p><img src="{% static image.image.url %}" alt="Bathroom in {{ bathroom.name }}"></p>
				{% endfor %}
			{% endif %}
			</div>
			
			<hr>
			
			<h2>Add a rating</h2>
			
			<form action="{% url 'bathrooms:vote' bathroom.id %}" method="post" onsubmit="return validateForm();">
				{% csrf_token %}
				<p>Cleanliness</p>
				<input type="radio" name="cleanliness" value="1" />
				<label for="1">1</label>

				<input type="radio" name="cleanliness" value="2" />
				<label for="2">2</label>

				<input type="radio" name="cleanliness" value="3" />
				<label for="3">3</label>

				<input type="radio" name="cleanliness" value="4" />
				<label for="4">4</label>

				<input type="radio" name="cleanliness" value="5" />
				<label for="5">5</label>

				<p>Amenities</p>
				<input type="radio" name="amenities" value="1" />
				<label for="1">1</label>

				<input type="radio" name="amenities" value="2" />
				<label for="2">2</label>

				<input type="radio" name="amenities" value="3" />
				<label for="3">3</label>

				<input type="radio" name="amenities" value="4" />
				<label for="4">4</label>

				<input type="radio" name="amenities" value="5" />
				<label for="5">5</label>

				<p><input id="submit" type="submit" value="Submit" /></p>
			</form>
			
			<p id="error"></p>
		</div>
	</div>
{% endif %}
{% endblock %}

bathrooms/templates/bathrooms/list.html
{% extends "bathrooms/template.html" %}

{% block content %}

<div id="title">
	<h1>Airpnp - {{ heading }}</h1>
	<p id="navbutton"><a href="{% url 'index' %}">About Airpnp</a></p>
</div>

{% if bathroom_list and length > 0 %}
	<table>
		<tr>
			<th>Bathroom</th>
			<th>Gender</th>
			<th>Location</th>
			<th>Cleanliness</th>
			<th>Amenities</th>
		</tr>
	{% for bathroom, rating in bathroom_list %}
		<tr>
			<td><a href="{% url 'bathrooms:detail' bathroom.id %}">{{ bathroom.name }}</a></td>
			<td>
				{% if bathroom.gender == 0 %} Men's {% endif %}
				{% if bathroom.gender == 1 %} Women's {% endif %}
				{% if bathroom.gender == 2 %} Gender-neutral {% endif %}
			</td>
			<td>{{ bathroom.location.human_readable_location }}</td>
			<td>{{ rating.cleanliness|safe|escape }}</td>
			<td>{{ rating.amenities|safe|escape }}</td>
		</tr>
	{% endfor %}
	</table>

{% else %}

<p>No bathrooms here :(</p>
<p>Unfortunately you'll have to take your business elsewhere.</p>	
	
{% endif %}

<p>Filter by: <a href="{% url 'bathrooms:list' %}">All</a> <a href="{% url 'bathrooms:list' %}?filtertype=singles">Singles</a> <a href="{% url 'bathrooms:list' %}?filtertype=mens">Men's</a> <a href="{% url 'bathrooms:list' %}?filtertype=womens">Women's</a> <a href="{% url 'bathrooms:list' %}?filtertype=genderneutral">Gender-neutral</a>
{% endblock %}

bathrooms/templates/bathrooms/template.html
<!doctype html>
<html>
	<head>
		<title>Airpnp</title>
		<meta charset="utf/8">
		<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=1">
		{% load static %}
		<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
		<script src="{% static 'script.js' %}"></script>
	</head>
	<body>
		{% block content %}{% endblock %}
	</body>
</html>

bathrooms/templates/index.html
<!doctype html>
<html>
	<head>
		<title>Airpnp</title>
		<meta charset="utf/8">
		<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=1">
		{% load static %}
		<link rel="stylesheet" type="text/css" href="{% static 'home.css' %}" />
	</head>
	<body>
		<header>
			<h1>Airpnp is the premiere bathroom catalog.</h1>

			<p>Airpnp is a leading global professional services company providing a range of enterprise, strategy, consulting, digital, technology & urination services and solutions.</p>
			
			<p id="button"><a href="{% url 'bathrooms:list' %}">See bathrooms</a></p>
		</header>
		
		<div id="but-actually">
			<h2>Peeing perfected</h2>
			<p>Airpnp was founded by a group of passionate code artisans devoted to bringing you the perfect on-campus bathroom experience.</p>
			
			<h2>Oh you thought we forgot to mention this was made with love</h2>
			<p>Lovingly built on top of jQuery, Angular.js, mongoDB, Express.js, Hadoop.js, Grunt.js, Gradle.js, Bootstrap, Firebase, Java.js Server.js Pages.js, Assembly, Calculator, Mavis Beacon Teaches Typing, and Love.js.</p>
		
			<h2>No, but seriously?</h2>
			<p>I made this at a hackathon to teach myself Django.</p>
			<p>The rest of my stuff is similarly bathroom-quality and is available <a href="http://theycallmezeal.me">on my website</a>.</p>
		</div>
	</body>
</html>